# Generated by Django 6.1 on 2026-09-11 17:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suministros', '0005_alter_pack_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('detalles', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('contrato', models.FileField(blank=True, null=True, upload_to='contratos/')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cif', models.CharField(max_length=9, unique=True)),
                ('correo', models.EmailField(max_length=254)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='proveedores/')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_maxima', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('suministro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_expediente', to='suministros.suministro')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_expediente', to='expedientes.expediente')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='expedientes.expediente')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('suministro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='suministros.suministro')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_pedido', to='expedientes.pedido')),
            ],
        ),
        migrations.AddField(
            model_name='expediente',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to='expedientes.proveedor'),
        ),
    ]
