# Generated by Django 6.1 on 2026-09-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0002_remove_detalleexpediente_cantidad_maxima_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='recibido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_pedido',
            field=models.CharField(choices=[('EXPEDIENTE', 'Con expediente'), ('GENERAL', 'Gasto general')], default='EXPEDIENTE', max_length=20),
            preserve_default=False,
        ),
    ]
