# Generated by Django 6.1 on 2026-09-13 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0003_pedido_recibido_pedido_tipo_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='activo',
        ),
    ]
