# Generated by Django 6.1 on 2026-09-14 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0004_remove_expediente_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='expedientes.proveedor'),
        ),
    ]
