# Generated by Django 6.1 on 2026-10-03 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0005_pedido_proveedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleexpediente',
            options={'verbose_name': 'Detalle de expediente', 'verbose_name_plural': 'Detalles de expediente'},
        ),
        migrations.AlterModelOptions(
            name='detallepedido',
            options={'verbose_name': 'Detalle de pedido', 'verbose_name_plural': 'Detalles de pedido'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
    ]
