# Generated by Django 6.1 on 2026-10-05 17:06

import config.archivos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0006_alter_detalleexpediente_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='contrato',
            field=models.FileField(blank=True, null=True, upload_to=config.archivos.RutaAleatoria('contratos')),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=config.archivos.RutaAleatoria('proveedores')),
        ),
    ]
