# Generated by Django 6.1 on 2026-10-03 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_historial_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historial',
            options={'ordering': ['-fecha'], 'verbose_name': 'Historial', 'verbose_name_plural': 'Historial'},
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fecha'], 'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
    ]
