# Generated by Django 6.1 on 2026-09-10 17:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suministros', '0005_alter_pack_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='BajaAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('PACK', 'Pack'), ('EXTRAORDINARIA', 'Extraordinaria')], max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('servicio', models.CharField(choices=[('LIMPIEZA', 'Limpieza'), ('COMIDA', 'Comida'), ('SANITARIO', 'Sanitario'), ('MANTENIMIENTO', 'Mantenimiento'), ('LAVANDERIA', 'Lavandería'), ('ADMINISTRACION', 'Administración'), ('ATENCION_RESIDENTES', 'Atención a residentes'), ('OTROS', 'Otros')], max_length=20, null=True)),
                ('entrega_pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bajas', to='suministros.entregapack')),
                ('suministro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bajas', to='suministros.suministro')),
            ],
        ),
    ]
