# Generated by Django 6.1 on 2026-09-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bajaalmacen',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
