# Generated by Django 6.1 on 2026-09-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_alter_bajaalmacen_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='bajaalmacen',
            name='stock_tras_baja',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
