# Generated by Django 6.1 on 2026-09-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_bajaalmacen_stock_tras_baja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bajaalmacen',
            name='tipo',
            field=models.CharField(choices=[('PACK', 'Pack'), ('SERVICIO', 'Servicio')], max_length=20),
        ),
    ]
