# Generated by Django 6.1 on 2026-09-12 21:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0004_alter_bajaalmacen_tipo'),
        ('expedientes', '0003_pedido_recibido_pedido_tipo_pedido'),
        ('suministros', '0005_alter_pack_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltaAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('factura_albaran', models.FileField(blank=True, null=True, upload_to='facturas_albaranes/')),
                ('stock_tras_alta', models.PositiveIntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='altas', to='expedientes.pedido')),
                ('suministro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='altas', to='suministros.suministro')),
            ],
        ),
    ]
