# Generated by Django 6.1 on 2026-10-03 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0005_altaalmacen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='altaalmacen',
            options={'verbose_name': 'Alta de almacén', 'verbose_name_plural': 'Altas de almacén'},
        ),
        migrations.AlterModelOptions(
            name='bajaalmacen',
            options={'verbose_name': 'Baja de almacén', 'verbose_name_plural': 'Bajas de almacén'},
        ),
    ]
