# Generated by Django 6.1 on 2026-10-05 17:06

import config.archivos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0006_alter_altaalmacen_options_alter_bajaalmacen_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altaalmacen',
            name='factura_albaran',
            field=models.FileField(blank=True, null=True, upload_to=config.archivos.RutaAleatoria('facturas_albaranes')),
        ),
    ]
