# Generated by Django 6.1 on 2026-09-06 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suministro',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suministros', to='suministros.categoria'),
        ),
    ]
