# Generated by Django 6.1 on 2026-09-08 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentes', '0001_initial'),
        ('suministros', '0003_alter_suministro_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntregaPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField(auto_now_add=True)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residentes.residente')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suministros.pack')),
            ],
        ),
        migrations.CreateModel(
            name='ContenidoPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('suministro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suministros.suministro')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suministros.pack')),
            ],
        ),
    ]
