# Generated by Django 6.1 on 2026-09-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0004_pack_entregapack_contenidopack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
