# Generated by Django 6.1 on 2026-10-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0005_alter_pack_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='contenidopack',
            options={'verbose_name': 'Contenido de pack', 'verbose_name_plural': 'Contenidos de pack'},
        ),
        migrations.AlterModelOptions(
            name='entregapack',
            options={'verbose_name': 'Entrega de pack', 'verbose_name_plural': 'Entregas de pack'},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
