# Generated by Django 6.1 on 2026-10-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0006_alter_categoria_options_alter_contenidopack_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='suministro',
            name='detalles',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
