# Generated by Django 6.1 on 2026-10-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0007_alter_categoria_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='descripcion',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
