# Generated by Django 6.1 on 2026-10-05 17:06

import config.archivos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=config.archivos.RutaAleatoria('usuarios')),
        ),
    ]
