# Generated by Django 6.1 on 2026-09-17 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centro',
            name='presupuesto_referencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
