# Generated by Django 6.1 on 2026-10-05 17:06

import config.archivos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0002_centro_presupuesto_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centro',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=config.archivos.RutaAleatoria('centro')),
        ),
    ]
