# Generated by Django 6.1 on 2026-08-31 18:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('info', models.TextField(blank=True)),
                ('capacidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='modulos.modulo')),
            ],
        ),
    ]
