# Generated by Django 6.1 on 2026-09-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0002_habitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='habitacion',
            constraint=models.UniqueConstraint(fields=('modulo', 'nombre'), name='unique_habitacion_por_modulo'),
        ),
    ]
