# Generated by Django 6.1 on 2026-09-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0003_alter_habitacion_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
