# Generated by Django 6.1 on 2026-09-03 17:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0004_alter_habitacion_nombre_alter_modulo_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='f_alta',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
