# Generated by Django 6.1 on 2026-09-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0005_habitacion_f_alta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='f_alta',
            field=models.DateField(),
        ),
    ]
