# Generated by Django 6.1 on 2026-10-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0006_alter_habitacion_f_alta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitacion',
            options={'verbose_name': 'Habitación', 'verbose_name_plural': 'Habitaciones'},
        ),
        migrations.AlterModelOptions(
            name='modulo',
            options={'verbose_name': 'Módulo', 'verbose_name_plural': 'Módulos'},
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='info',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='descripcion',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
