# Generated by Django 6.1 on 2026-09-01 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulos', '0004_alter_habitacion_nombre_alter_modulo_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=9)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('f_nacimiento', models.DateField()),
                ('f_alta', models.DateField()),
                ('f_baja', models.DateField(blank=True, null=True)),
                ('info', models.TextField(blank=True)),
                ('pais', models.CharField(max_length=100)),
                ('dni_nie', models.CharField(max_length=20, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='residentes/')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('habitacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residentes', to='modulos.habitacion')),
            ],
        ),
    ]
