# Generated by Django 6.1 on 2026-10-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residente',
            name='dni_nie',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
