# Generated by Django 6.1 on 2026-10-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentes', '0002_alter_residente_dni_nie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residente',
            name='info',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
