# Generated by Django 6.1 on 2026-10-05 17:06

import config.archivos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentes', '0003_alter_residente_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=config.archivos.RutaAleatoria('residentes')),
        ),
    ]
